# Generated by Django 5.2.4 on 2025-07-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('url', models.URLField(unique=True)),
                ('category', models.CharField(max_length=50)),
                ('published_at', models.DateTimeField()),
            ],
        ),
    ]
